import "./globals.css";
import { Roboto } from "next/font/google";
import Nav from "./auth/Nav";
import { ReactNode } from "react";
import QueryWrapper from "./auth/QueryWrapper";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Prisma Tweet",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} mx-4 md:mx-48 xl:mx-96 bg-slate-50 px-6`}
      >
        <QueryWrapper>
          {" "}
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  );
}
