import "./globals.css";
import { Roboto } from "next/font/google";
import Nav from "./auth/Nav";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Prisma Tweet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} mx-4 md:mx-48 xl:mx-96 bg-slate-50 px-6`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
